---
spring:
  application:
    name: eureka-server-single
  profiles: default

server:
  port: 8010

#This cfg is for single instance of eureka server, not recommended in production
#Only for testing
eureka:
  instance:
    hostname: eurekahost

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka





---

#This is given for production env where at least 3 instances of eureka server should run together so that if
#one server fails other could be its backup
# primary, secondary, and tertiary illustrate running 3 inter-communicating instances.
#  This example has them running side-by-side on localhost -- which is unrealistic in production
#  -- but does illustrate how multiple instances collaborate.

# Run by opening 3 separate command prompts:
# java -jar -Dspring.profiles.active=primary <app-name>.jar
# java -jar -Dspring.profiles.active=secondary <app-name>.jar
# java -jar -Dspring.profiles.active=tertiary <app-name>.jar


spring:
  application:
    name: eureka-server-clustered
  profiles: primary

server:
  port: 8011

eureka:
  instance:
    hostname: eureka-primary
    appname: eureka-cluster
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
      # defaultZone: http://localhost:8012/eureka/,http://localhost:8013/eureka/




---
spring:
  profiles: secondary

server:
  port: 8012

eureka:
  instance:
    hostname: eureka-secondary
    appname: eureka-cluster
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-tertiary:8013/eureka/,http://eureka-primary:8011/eureka/
#      defaultZone: http://localhost:8013/eureka/,http://localhost:8011/eureka/



---
spring:
  profiles: tertiary

server:
  port: 8013

eureka:
  instance:
    hostname: eureka-tertiary
    appname: eureka-cluster
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-secondary:8012/eureka/,http://eureka-primary:8011/eureka/
      # defaultZone: http://localhost:8012/eureka/,http://localhost:8011/eureka/
